export interface EmbeddedStageDescriptor {
  xmlName: string;
  displayName: string;
  imageUrl: string | null;
  canonicalOrder: number;
  isRandom: boolean;
}

export const EMBEDDED_STAGE_LAYOUT: EmbeddedStageDescriptor[] = [
  { xmlName: 'Random', displayName: 'Random', imageUrl: null, canonicalOrder: 0, isRandom: true },
  { xmlName: 'RandomNormal', displayName: 'RandomNormal', imageUrl: null, canonicalOrder: 0, isRandom: true },
  { xmlName: 'RandomBattleField', displayName: 'RandomBattleField', imageUrl: null, canonicalOrder: 0, isRandom: true },
  { xmlName: 'RandomEnd', displayName: 'RandomEnd', imageUrl: null, canonicalOrder: 0, isRandom: true },
  { xmlName: 'BattleField', displayName: 'Battlefield', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img1.jpg', canonicalOrder: 1, isRandom: false },
  { xmlName: 'BattleFieldS', displayName: 'Small Battlefield', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img104.jpg', canonicalOrder: 2, isRandom: false },
  { xmlName: 'BattleFieldL', displayName: 'Big Battlefield', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img2.jpg', canonicalOrder: 3, isRandom: false },
  { xmlName: 'End', displayName: 'Final Destination', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img3.jpg', canonicalOrder: 4, isRandom: false },
  { xmlName: 'Mario_Castle64', displayName: 'Peach\'s Castle', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img4.jpg', canonicalOrder: 5, isRandom: false },
  { xmlName: 'DK_Jungle', displayName: 'Kongo Jungle', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img5.jpg', canonicalOrder: 6, isRandom: false },
  { xmlName: 'Zelda_Hyrule', displayName: 'Hyrule Castle', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img6.jpg', canonicalOrder: 7, isRandom: false },
  { xmlName: 'Yoshi_Story', displayName: 'Super Happy Tree', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img7.jpg', canonicalOrder: 8, isRandom: false },
  { xmlName: 'Kirby_Pupupu64', displayName: 'Dream Land', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img8.jpg', canonicalOrder: 9, isRandom: false },
  { xmlName: 'Poke_Yamabuki', displayName: 'Saffron City', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img9_en.jpg', canonicalOrder: 10, isRandom: false },
  { xmlName: 'Mario_Past64', displayName: 'Mushroom Kingdom', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img10.jpg', canonicalOrder: 11, isRandom: false },
  { xmlName: 'Mario_CastleDx', displayName: 'Princess Peach\'s Castle', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img11.jpg', canonicalOrder: 12, isRandom: false },
  { xmlName: 'Mario_Rainbow', displayName: 'Rainbow Cruise', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img12.jpg', canonicalOrder: 13, isRandom: false },
  { xmlName: 'DK_WaterFall', displayName: 'Kongo Falls', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img13.jpg', canonicalOrder: 14, isRandom: false },
  { xmlName: 'DK_Lodge', displayName: 'Jungle Japes', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img14.jpg', canonicalOrder: 15, isRandom: false },
  { xmlName: 'Zelda_Greatbay', displayName: 'Great Bay', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img15.jpg', canonicalOrder: 16, isRandom: false },
  { xmlName: 'Zelda_Temple', displayName: 'Temple', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img16.jpg', canonicalOrder: 17, isRandom: false },
  { xmlName: 'Metroid_ZebesDx', displayName: 'Brinstar', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img17.jpg', canonicalOrder: 18, isRandom: false },
  { xmlName: 'Yoshi_Yoster', displayName: 'Yoshi\'s Island (Melee)', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img18.jpg', canonicalOrder: 19, isRandom: false },
  { xmlName: 'Yoshi_CartBoard', displayName: 'Yoshi\'s Story', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img19.jpg', canonicalOrder: 20, isRandom: false },
  { xmlName: 'Kirby_Fountain', displayName: 'Fountain of Dreams', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img20.jpg', canonicalOrder: 21, isRandom: false },
  { xmlName: 'Kirby_Greens', displayName: 'Green Greens', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img21.jpg', canonicalOrder: 22, isRandom: false },
  { xmlName: 'Fox_Corneria', displayName: 'Corneria', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img22.jpg', canonicalOrder: 23, isRandom: false },
  { xmlName: 'Fox_Venom', displayName: 'Venom', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img23.jpg', canonicalOrder: 24, isRandom: false },
  { xmlName: 'Poke_Stadium', displayName: 'Pokemon Stadium', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img24.jpg', canonicalOrder: 25, isRandom: false },
  { xmlName: 'Mother_Onett', displayName: 'Onett', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img25.jpg', canonicalOrder: 26, isRandom: false },
  { xmlName: 'Mario_PastUsa', displayName: 'Mushroom Kingdom II', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img26.jpg', canonicalOrder: 27, isRandom: false },
  { xmlName: 'Metroid_Kraid', displayName: 'Brinstar Depths', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img27.jpg', canonicalOrder: 28, isRandom: false },
  { xmlName: 'Fzero_Bigblue', displayName: 'Big Blue', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img28.jpg', canonicalOrder: 29, isRandom: false },
  { xmlName: 'Mother_Fourside', displayName: 'Fourside', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img29.jpg', canonicalOrder: 30, isRandom: false },
  { xmlName: 'Mario_Dolpic', displayName: 'Delfino Plaza', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img30.jpg', canonicalOrder: 31, isRandom: false },
  { xmlName: 'Mario_PastX', displayName: 'Mushroomy Kingdom', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img31.jpg', canonicalOrder: 32, isRandom: false },
  { xmlName: 'Kart_CircuitX', displayName: 'Figure-8 Circuit', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img32.jpg', canonicalOrder: 33, isRandom: false },
  { xmlName: 'Wario_Madein', displayName: 'WarioWare, Inc.', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img33.jpg', canonicalOrder: 34, isRandom: false },
  { xmlName: 'Zelda_Oldin', displayName: 'Bridge of Eldin', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img34.jpg', canonicalOrder: 35, isRandom: false },
  { xmlName: 'Metroid_Norfair', displayName: 'Norfair', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img35.jpg', canonicalOrder: 36, isRandom: false },
  { xmlName: 'Metroid_Orpheon', displayName: 'Frigate Orpheon', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img36.jpg', canonicalOrder: 37, isRandom: false },
  { xmlName: 'Yoshi_Island', displayName: 'Yoshi\'s Island', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img37.jpg', canonicalOrder: 38, isRandom: false },
  { xmlName: 'Kirby_Halberd', displayName: 'Halberd', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img38.jpg', canonicalOrder: 39, isRandom: false },
  { xmlName: 'Fox_LylatCruise', displayName: 'Lylat Cruise', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img39.jpg', canonicalOrder: 40, isRandom: false },
  { xmlName: 'Poke_Stadium2', displayName: 'Pokemon Stadium 2', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img40.jpg', canonicalOrder: 41, isRandom: false },
  { xmlName: 'Fzero_Porttown', displayName: 'Port Town Aero Dive', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img41.jpg', canonicalOrder: 42, isRandom: false },
  { xmlName: 'FE_Siege', displayName: 'Castle Siege', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img42.jpg', canonicalOrder: 43, isRandom: false },
  { xmlName: 'Pikmin_Planet', displayName: 'Distant Planet', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img43.jpg', canonicalOrder: 44, isRandom: false },
  { xmlName: 'Animal_Village', displayName: 'Smashville', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img44.jpg', canonicalOrder: 45, isRandom: false },
  { xmlName: 'Mother_Newpork', displayName: 'New Pork City', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img45.jpg', canonicalOrder: 46, isRandom: false },
  { xmlName: 'Ice_Top', displayName: 'Summit', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img46.jpg', canonicalOrder: 47, isRandom: false },
  { xmlName: 'Icarus_SkyWorld', displayName: 'Skyworld', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img47.jpg', canonicalOrder: 48, isRandom: false },
  { xmlName: 'MG_Shadowmoses', displayName: 'Shadow Moses Island', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img48.jpg', canonicalOrder: 49, isRandom: false },
  { xmlName: 'LuigiMansion', displayName: 'Luigi\'s Mansion', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img49.jpg', canonicalOrder: 50, isRandom: false },
  { xmlName: 'Zelda_Pirates', displayName: 'Pirate Ship', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img50.jpg', canonicalOrder: 51, isRandom: false },
  { xmlName: 'Poke_Tengam', displayName: 'Spear Pillar', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img51.jpg', canonicalOrder: 52, isRandom: false },
  { xmlName: '75m', displayName: '75 m', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img52.jpg', canonicalOrder: 53, isRandom: false },
  { xmlName: 'MarioBros', displayName: 'Mario Bros.', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img53.jpg', canonicalOrder: 54, isRandom: false },
  { xmlName: 'Plankton', displayName: 'Hanenbow', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img54.jpg', canonicalOrder: 55, isRandom: false },
  { xmlName: 'Sonic_Greenhill', displayName: 'Green Hill Zone', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img55.jpg', canonicalOrder: 56, isRandom: false },
  { xmlName: 'Mario_3DLand', displayName: '3D Land', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img56.jpg', canonicalOrder: 57, isRandom: false },
  { xmlName: 'Mario_NewBros2', displayName: 'Golden Plains', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img57.jpg', canonicalOrder: 58, isRandom: false },
  { xmlName: 'Mario_Paper', displayName: 'Paper Mario', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img58.jpg', canonicalOrder: 59, isRandom: false },
  { xmlName: 'Zelda_Gerudo', displayName: 'Gerudo Valley', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img59.jpg', canonicalOrder: 60, isRandom: false },
  { xmlName: 'Zelda_Train', displayName: 'Spirit Train', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img60.jpg', canonicalOrder: 61, isRandom: false },
  { xmlName: 'Kirby_Gameboy', displayName: 'Dream Land GB', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img61.jpg', canonicalOrder: 62, isRandom: false },
  { xmlName: 'Poke_Unova', displayName: 'Unova Pokemon League', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img62.jpg', canonicalOrder: 63, isRandom: false },
  { xmlName: 'Poke_Tower', displayName: 'Prism Tower', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img63.jpg', canonicalOrder: 64, isRandom: false },
  { xmlName: 'Fzero_Mutecity3DS', displayName: 'Mute City SNES', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img64.jpg', canonicalOrder: 65, isRandom: false },
  { xmlName: 'Mother_Magicant', displayName: 'Magicant', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img65.jpg', canonicalOrder: 66, isRandom: false },
  { xmlName: 'FE_Arena', displayName: 'Arena Ferox', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img66.jpg', canonicalOrder: 67, isRandom: false },
  { xmlName: 'Icarus_Uprising', displayName: 'Reset Bomb Forest', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img67.jpg', canonicalOrder: 68, isRandom: false },
  { xmlName: 'Animal_Island', displayName: 'Tortimer Island', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img68.jpg', canonicalOrder: 69, isRandom: false },
  { xmlName: 'BalloonFight', displayName: 'Balloon Fight', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img69.jpg', canonicalOrder: 70, isRandom: false },
  { xmlName: 'NintenDogs', displayName: 'Living Room', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img70.jpg', canonicalOrder: 71, isRandom: false },
  { xmlName: 'StreetPass', displayName: 'Find Mii', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img71.jpg', canonicalOrder: 72, isRandom: false },
  { xmlName: 'Tomodachi', displayName: 'Tomodachi Life', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img72.jpg', canonicalOrder: 73, isRandom: false },
  { xmlName: 'Pictochat2', displayName: 'PictoChat 2', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img73_en.jpg', canonicalOrder: 74, isRandom: false },
  { xmlName: 'Mario_Uworld', displayName: 'Mushroom Kingdom U', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img74.jpg', canonicalOrder: 75, isRandom: false },
  { xmlName: 'Mario_Galaxy', displayName: 'Mario Galaxy', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img75.jpg', canonicalOrder: 76, isRandom: false },
  { xmlName: 'Kart_CircuitFor', displayName: 'Mario Circuit', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img76.jpg', canonicalOrder: 77, isRandom: false },
  { xmlName: 'Zelda_Skyward', displayName: 'Skyloft', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img77.jpg', canonicalOrder: 78, isRandom: false },
  { xmlName: 'Kirby_Cave', displayName: 'The Great Cave Offensive', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img78.jpg', canonicalOrder: 79, isRandom: false },
  { xmlName: 'Poke_Kalos', displayName: 'Kalos Pokemon League', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img79.jpg', canonicalOrder: 80, isRandom: false },
  { xmlName: 'FE_Colloseum', displayName: 'Coliseum', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img80.jpg', canonicalOrder: 81, isRandom: false },
  { xmlName: 'FlatZoneX', displayName: 'Flat Zone X', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img81_en.jpg', canonicalOrder: 82, isRandom: false },
  { xmlName: 'Icarus_Angeland', displayName: 'Palutena\'s Temple', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img82.jpg', canonicalOrder: 83, isRandom: false },
  { xmlName: 'Wario_Gamer', displayName: 'Gamer', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img83.jpg', canonicalOrder: 84, isRandom: false },
  { xmlName: 'Pikmin_Garden', displayName: 'Garden of Hope', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img84.jpg', canonicalOrder: 85, isRandom: false },
  { xmlName: 'Animal_City', displayName: 'Town and City', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img85_en.jpg', canonicalOrder: 86, isRandom: false },
  { xmlName: 'WiiFit', displayName: 'Wii Fit Studio', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img86.jpg', canonicalOrder: 87, isRandom: false },
  { xmlName: 'PunchOutSB', displayName: 'Boxing Ring', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img87.jpg', canonicalOrder: 88, isRandom: false },
  { xmlName: 'Xeno_Gaur', displayName: 'Gaur Plain', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img88.jpg', canonicalOrder: 89, isRandom: false },
  { xmlName: 'DuckHunt', displayName: 'Duck Hunt', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img89.jpg', canonicalOrder: 90, isRandom: false },
  { xmlName: 'WreckingCrew', displayName: 'Wrecking Crew', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img90.jpg', canonicalOrder: 91, isRandom: false },
  { xmlName: 'Pilotwings', displayName: 'Pilotwings', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img91.jpg', canonicalOrder: 92, isRandom: false },
  { xmlName: 'WufuIsland', displayName: 'Wuhu Island', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img92.jpg', canonicalOrder: 93, isRandom: false },
  { xmlName: 'Sonic_Windyhill', displayName: 'Windy Hill Zone', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img93.jpg', canonicalOrder: 94, isRandom: false },
  { xmlName: 'Rock_Wily', displayName: 'Wily Castle', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img94.jpg', canonicalOrder: 95, isRandom: false },
  { xmlName: 'Pac_Land', displayName: 'PAC-LAND', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img95.jpg', canonicalOrder: 96, isRandom: false },
  { xmlName: 'Mario_Maker', displayName: 'Super Mario Maker', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img96.jpg', canonicalOrder: 97, isRandom: false },
  { xmlName: 'SF_Suzaku', displayName: 'Suzaku Castle', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img97.jpg', canonicalOrder: 98, isRandom: false },
  { xmlName: 'FF_Midgar', displayName: 'Midgar', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img98.jpg', canonicalOrder: 99, isRandom: false },
  { xmlName: 'Bayo_Clock', displayName: 'Umbra Clock Tower', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img99.jpg', canonicalOrder: 100, isRandom: false },
  { xmlName: 'Mario_Odyssey', displayName: 'New Donk City Hall', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img100.jpg', canonicalOrder: 101, isRandom: false },
  { xmlName: 'Zelda_Tower', displayName: 'Great Plateau Tower', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img101.jpg', canonicalOrder: 102, isRandom: false },
  { xmlName: 'Spla_Parking', displayName: 'Moray Towers', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img102.jpg', canonicalOrder: 103, isRandom: false },
  { xmlName: 'Dracula_Castle', displayName: 'Dracula\'s Castle', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_img103.jpg', canonicalOrder: 104, isRandom: false },
  { xmlName: 'Jack_Mementoes', displayName: 'Mementos', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img1.jpg', canonicalOrder: 105, isRandom: false },
  { xmlName: 'Brave_Altar', displayName: 'Yggdrasil\'s Altar', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img2.jpg', canonicalOrder: 106, isRandom: false },
  { xmlName: 'Buddy_Spiral', displayName: 'Spiral Mountain', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img3.jpg', canonicalOrder: 107, isRandom: false },
  { xmlName: 'Dolly_Stadium', displayName: 'King of Fighters Stadium', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img4.jpg', canonicalOrder: 108, isRandom: false },
  { xmlName: 'FE_Shrine', displayName: 'Garreg Mach Monastery', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img5.jpg', canonicalOrder: 109, isRandom: false },
  { xmlName: 'Tantan_Spring', displayName: 'Spring Stadium', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img6.jpg', canonicalOrder: 110, isRandom: false },
  { xmlName: 'Pickel_World', displayName: 'Minecraft World', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img7.jpg', canonicalOrder: 111, isRandom: false },
  { xmlName: 'FF_Cave', displayName: 'Northern Cave', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img8.jpg', canonicalOrder: 112, isRandom: false },
  { xmlName: 'Xeno_Alst', displayName: 'Cloud Sea of Alrest', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img9.jpg', canonicalOrder: 113, isRandom: false },
  { xmlName: 'Demon_Dojo', displayName: 'Mishima Dojo', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img10.jpg', canonicalOrder: 114, isRandom: false },
  { xmlName: 'Trail_Castle', displayName: 'Hollow Bastion', imageUrl: 'https://www.smashbros.com/assets_v2/img/stage/stage_addition_img11.jpg', canonicalOrder: 115, isRandom: false },
];
